### ISSUE TITLE
Suggestion + issues

### ISSUE THREAD

**Issue by pronoyb07** [vijethx/waveportal-frontend#2]
Do a micro-interaction on the "wave at me" button and read about "[different states of buttons](https://xd.adobe.com/ideas/process/ui-design/designing-interactive-buttons-states/)"

Add options to collet different wallets eg. metamask, coinbase, wallet connect, etc
Right now the issue is when I click on connect wallet my metamask & coinbase wallet wallets are opening simultaneously

Try to communicate with the user in some way, one way to do it can be via when I click on "wave at me" button a pop appears saying "thinking for waving at me", or "Hello from the other side"([adele ref.](https://youtu.be/YQHsXMglC9A?t=140))
+ add some confetti when user waves at ya

**Comment by vijethx** [comment]
sorted most of the things
